# ========== DOSYA: app-weather-forecaster/src/azuraforge_weatherapp/config/weather_forecaster_config.yml ==========
# Bu, bu eklenti için "altın standart" varsayılan konfigürasyondur.
# "Kutudan çıktığı gibi" iyi sonuçlar vermesi hedeflenmiştir.

pipeline_name: "weather_forecaster"

data_sourcing:
  latitude: 36.9013
  longitude: 30.6651
  hourly_vars:
    - "relative_humidity_2m"
    - "precipitation"
    - "cloud_cover"
  # Varsayılan olarak son 1 yıllık (~8760 satır) veriyi kullan.
  # Hızlı testler için bu değer `run_isolated.py` ile değiştirilebilir.
  data_limit: 8760

feature_engineering:
  target_col: "temperature_2m"
  target_col_transform: "none"

model_params:
  sequence_length: 168  # 7 günlük geçmişe bak
  hidden_size: 64       # Yüksek kapasiteli model

training_params:
  epochs: 30            # Yeterli eğitim süresi
  lr: 0.001
  optimizer: "adam"
  test_size: 0.2
  validate_every: 5
  batch_size: 32        # VRAM dostu yığın boyutu

system:
  caching_enabled: true
  cache_max_age_hours: 6