# ========== DOSYA: app-weather-forecaster/src/azuraforge_weatherapp/config/weather_forecaster_config.yml ==========
# Bu, bu eklenti için "altın standart" varsayılan konfigürasyondur.
# Hem yapısal olarak sağlıklı (düşük bias) hem de metrik olarak
# yüksek performanslı (R² > 0.90) sonuçlar üretmesi hedeflenmiştir.

pipeline_name: "weather_forecaster"

data_sourcing:
  latitude: 36.9013
  longitude: 30.6651
  hourly_vars:
    - "relative_humidity_2m"
    - "precipitation"
    - "cloud_cover"
  data_limit: 8760

feature_engineering:
  target_col: "temperature_2m"
  target_col_transform: "none"

model_params:
  sequence_length: 168
  hidden_size: 128      # <-- YENİ NİHAİ DEĞER

training_params:
  epochs: 50            # <-- YENİ NİHAİ DEĞER
  lr: 0.001
  optimizer: "adam"
  test_size: 0.2
  validate_every: 5
  batch_size: 32

system:
  caching_enabled: true
  cache_max_age_hours: 6